battle_type: Map
friend_fleet:
  side: 1
  form: 5
  ships:
  - loc: 1
    cid: '10586'
    level: 110
    affection: 200
    skill: 1
    equipment:
    - loc: 1
      eid: '10657'
    - loc: 2
      eid: '10726'
    - loc: 3
      eid: '10695'
    - loc: 4
      eid: '10342'
    strategy:
    - stid: '231'
      level: 3
  - loc: 2
    cid: '10202'
    level: 110
    affection: 200
    skill: 1
    equipment:
    - loc: 1
      eid: '10721'
    - loc: 2
      eid: '10518'
    - loc: 3
      eid: '10130'
    - loc: 4
      eid: '10129'
    strategy:
    - stid: '131'
      level: 3
  - loc: 3
    cid: '10613'
    level: 110
    affection: 200
    skill: 1
    input_health: 50
    equipment:
    - loc: 1
      eid: '10727'
    - loc: 2
      eid: '10518'
    - loc: 3
      eid: '10728'
    - loc: 4
      eid: '10518'
    strategy: []
  - loc: 4
    cid: '10559'
    level: 110
    affection: 200
    skill: 1
    equipment:
    - loc: 1
      eid: '10655'
    - loc: 2
      eid: '10654'
    - loc: 3
      eid: '10654'
    strategy: []
  - loc: 5
    cid: '10601'
    level: 110
    affection: 200
    skill: 1
    equipment:
    - loc: 1
      eid: '10713'
    - loc: 2
      eid: '10712'
    - loc: 3
      eid: '10373'
    strategy: []
  - loc: 6
    cid: '11097'
    level: 110
    affection: 200
    skill: 1
    equipment:
    - loc: 1
      eid: '10638'
    - loc: 2
      eid: '10705'
    - loc: 3
      eid: '10705'
    strategy: []
map:
  mapid: 2-1
